### ISSUE TITLE
Nested markdown in HTML

### ISSUE THREAD

**Issue by rubensworks** [LinkedSoftwareDependencies/Article-Reproducability#12]
Currently, nesting markdown in html is not possible, as can be seen here: https://linkedsoftwaredependencies.github.io/Article-Reproducability/#use-case

If it's not a trivial thing to implement, we need to manually make it so that the mandatory links inside these HTML blocks are included in the paper.

**Comment by RubenVerborgh** [comment]
Is [is possible](https://kramdown.gettalong.org/syntax.html):

> If an HTML tag has an attribute markdown="0", then the tag is parsed as raw HTML block.
>
> If an HTML tag has an attribute markdown="1", then the default mechanism for parsing syntax in this tag is used.
>
> If an HTML tag has an attribute markdown="block", then the content of the tag is parsed as block level elements.
>
> If an HTML tag has an attribute markdown="span", then the content of the tag is parsed as span level elements.

**Comment by RubenVerborgh** [comment]
(don't indent things though)

**Comment by rubensworks** [comment]
Nice! Forget I said anything then :-)
