### ISSUE TITLE
Set up canonical URL

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Article-Reproducability#13]
https://linkedsoftwaredependencies.org/articles/reproducibility/

**Comment by rubensworks** [comment]
Configured as
```
location /articles/reproducibility {
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass https://linkedsoftwaredependencies.github.io/Article-Reproducability/;
}
```
but stylesheets are not being forwarded for some reason.

Can't get it to work now, will focus on the paper first.

**Comment by RubenVerborgh** [comment]
Slash after reproducibility?

**Comment by rubensworks** [comment]
Already tried that, doesn't seem to work either.

Also tried some regex things, which wasn't successful either.

Maybe GitHub is blocking those forwards, but that seems unlikely.

**Comment by RubenVerborgh** [comment]
Ok, I'll look at it later today!

**Comment by rubensworks** [comment]
Ok, TIL some more about location matching in nginx,

There was a regex-based location after that block, which captures the assets,
adding `location ^~ /articles/reproducibility/` fixed it.
