### ISSUE TITLE
Sidenote

### ISSUE THREAD

**Issue by rubensworks** [LinkedSoftwareDependencies/Article-Reproducability#5]
An alternative for footnotes would be nice.

Now I use `<sidenote>` as a placeholder.

**Comment by RubenVerborgh** [comment]
The build is broken because of this: https://travis-ci.org/LinkedSoftwareDependencies/Article-Reproducability/builds/230256058

Could you fix this with a different placeholder?

**Comment by rubensworks** [comment]
Now using `<aside>`

**Comment by RubenVerborgh** [comment]
kramdown has [footnote support](https://kramdown.gettalong.org/quickref.html#footnotes).

**Comment by RubenVerborgh** [comment]
(I'll just style them better.)
