### ISSUE TITLE
Enumerations

### ISSUE THREAD

**Issue by rubensworks** [LinkedSoftwareDependencies/Article-Reproducability#6]
Ordered and unordered list support, either with HTML tags (`<ol>`, `<ul>`) or markdown (`*`).

**Comment by RubenVerborgh** [comment]
It is full markdown (even kramdown), so this is supported, certainly with `-`. Be sure to have a blank line before and after your lists.

**Comment by rubensworks** [comment]
Ah, you're right, I forgot about the blank newlines.
