### ISSUE TITLE
Link to foaf profiles

### ISSUE THREAD

**Issue by rubensworks** [LinkedSoftwareDependencies/Article-Reproducability#7]
Authors should have their foaf profiles linked.

**Comment by rubensworks** [comment]
Added links for everyone except for @joachimvh (Time to make a profile! 😉)

Perhaps we could also include a part of the profile, not sure about that.
@RubenVerborgh WDYT?

**Comment by RubenVerborgh** [comment]
The link itself should probably go to our websites; the FOAF IRI is used for identification. Perhaps check the http://csarven.ca/dokieli-rww example?

**Comment by rubensworks** [comment]
I would think we need exactly the FOAF identification here, no?
We want to identify the person, not the website.
The FOAF profile can then link to the website.

**Comment by RubenVerborgh** [comment]
Both: my website is the best link for me, so that should be the `href`. But I am indeed not my website, so we should have a `resource` IRI indicating me.

PS I have an IRI for Joachim: https://data.verborgh.org/people/joachim_van_herwegen

**Comment by rubensworks** [comment]
Added a method to link to FOAF profiles and websites.

@joachimvh Feel free to change your website if needed.

**Comment by joachimvh** [comment]
Neh I'm good

**Comment by csarven** [comment]
Alternative to Joachim being *brought to you by* Ruben, I think document's `#Joachim-Van-Herwegen` is ok. I've defaulted to that in some articles and proceedings for people that didn't have a profile or unable to determine.

**Comment by RubenVerborgh** [comment]
> Alternative to Joachim being brought to you by Ruben, I think document's #Joachim-Van-Herwegen is ok. 

Why create another identifier for something that already exists? That goes against the LD principles :-)
"My" https://data.verborgh.org/people/joachim_van_herwegen is already complete publication-wise, and I'd be happy to redirect it to whatever profile IRI @joachimvh chooses if he publishes his own.

**Comment by rubensworks** [comment]
Already fixed a while ago
